### ISSUE TITLE
Link to bundler project sites somewhere

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/tooling.report#245]
@argyleink any thoughts on where to put them?

**Comment by awayken** [comment]
I'm taking a stab at a pretty simple implementation for this. Do we think the images should have links around them, too? Or just the name of the tool?

This is what I have so far.

`<SummaryCard>`:
![image](https://user-images.githubusercontent.com/156215/88959699-05905c00-d268-11ea-813e-c1b777e00fc8.png)

`<ToolNav>`:
![image](https://user-images.githubusercontent.com/156215/88959766-235dc100-d268-11ea-9e20-1733768285e1.png)

**Comment by argyleink** [comment]
thanks @awayken! 
i'm down to keep it simple and just do the links 👍
