### ISSUE TITLE
Test detail score badge logos should link in page like the tool titles do

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/tooling.report#277]
![Screen Shot 2020-05-18 at 7 56 23 AM](https://user-images.githubusercontent.com/1134620/82227844-29850800-98dd-11ea-91e1-78589571657c.png)

**Comment by pajaydev** [comment]
@surma  I would like to take this one if it's unassigned. If I am not wrong, we need to make the logos as link like the titles do ?.

**Comment by surma** [comment]
Yeah give it try @pajaydev :D Open a PR and we can start reviewing :)

**Comment by pajaydev** [comment]
Cool 👍

**Comment by pajaydev** [comment]
@argyleink  I have made the change, kindly verify

**Comment by surma** [comment]
(@developit unrelated, any idea why the preview script isn’t running on this one?)
