### ISSUE TITLE
Horizontal scroll caused by Overview section

### ISSUE THREAD

**Issue by GuskiS** [GoogleChromeLabs/tooling.report#332]
Chrome: Version 83.0.4103.116 (Official Build) (64-bit)
OS: Ubuntu 18.04.4 LTS

Same thing appears on Firefox.

**Comment by GuskiS** [comment]
Caused by Overview section.

**Comment by jakearchibald** [comment]
I haven't been able to recreate this. Which page, and what browser width?

**Comment by GuskiS** [comment]
Take a look at screenshot, it seems to be problem on min-width: 1400px for Overview section. 
![image](https://user-images.githubusercontent.com/3505777/86112300-75c48a00-bad0-11ea-8432-31ba7cf503c0.png)

**Comment by jakearchibald** [comment]
Ah, I can recreate this on mac too by enabling permanent scrollbars

**Comment by jakearchibald** [comment]
Also, this only happens at particularly wide sizes. As in, when the site centres itself.

**Comment by jakearchibald** [comment]
Ok, this is caused by a 100vw, which (like other bits of CSS) doesn't deduct scrollbar width. We missed this because we're all using macs 😢 

Not sure the fix is straight forward. The full width of the overview element is kinda hacked in. Working on it…

**Comment by GuskiS** [comment]
It feels like you should remove max-width from `main` and add it to all `section` elements with `margin: 0 auto;` except overview. But not sure how that affects other styles.

**Comment by jakearchibald** [comment]
@GuskiS that isn't far off what I ended up doing https://github.com/GoogleChromeLabs/tooling.report/pull/338. Every time I've applied a width on one element, then tried to 'break out' back to full width, it's gone wrong at some point down the line.

**Comment by jakearchibald** [comment]
Fix deployed. Thanks for reporting this!
