### ISSUE TITLE
Brought to you by Web.dev, should ideally link to web.dev

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/tooling.report#344]
<img width="235" alt="Screenshot 2020-06-30 at 13 57 17" src="https://user-images.githubusercontent.com/45510/86128746-afe65980-bad9-11ea-8c05-37308c3802f8.png">

My natural reaction was to click on it, you could link to your launch blog post.

**Comment by surma** [comment]
On it
