### ISSUE TITLE
Would love to see a report on Vite

### ISSUE THREAD

**Issue by xerosanyam** [GoogleChromeLabs/tooling.report#347]
Hey guys, great work on the tool.
As Vite is catching up, and Vue3 is round the corner.. I am sure many devs would be interested in seeing a comparison of Vite with other tools. Ofcourse it is very early for Vite, but still a small overview from team (maybe just for knowledge) would be highly beneficial.

Thanks!

**Comment by jakearchibald** [comment]
Vite is built on top of Rollup, so in some ways it's already covered. However, it does ship with custom plugins that might be worth exploring. I'm going to close this, but it's tagged for us to find later.

**Comment by developit** [comment]
Moved to project board: https://github.com/GoogleChromeLabs/tooling.report/projects/2#card-38432765
