### ISSUE TITLE
New test: Ability to convert node-style import to a http url

### ISSUE THREAD

**Issue by Jack-Works** [GoogleChromeLabs/tooling.report#360]
```javascript
import React from 'react'
```

tools may output:

```javascript
import React from 'https://cdn.pika.dev/react@16.3.1'
```

**Comment by surma** [comment]
This seems like a DX feature to me. I don’t see how end-users benefit from this. If anything, it seems to me that it will impact loading performance negatively on average.

**Comment by Jack-Works** [comment]
Maybe Benefit from cdn?

**Comment by surma** [comment]
Ideally the dependencies sit on the same CDN as the app itself to avoid having to set up an additional connection. So the end-user benefit of this feature is very tangential, I think.

Going to close this as we don’t include DX features for now, but we can come back to this in the future if we ever start evaluating DX.
