### ISSUE TITLE
new tool: add esbuild - an extremely fast JavaScript bundler and minifier 

### ISSUE THREAD

**Issue by rajveermalviya** [GoogleChromeLabs/tooling.report#375]
https://github.com/evanw/esbuild

`ebuild` is written in Golang, unlike *many/all* other web bundlers, so it's already ahead in terms of performance.

It would be great to see where it stands in compatibility.

also, cc @evanw

**Comment by jakearchibald** [comment]
Thanks! We're already tracking this in https://github.com/GoogleChromeLabs/tooling.report/projects/2
