### ISSUE TITLE
Scores should also include perf and bundle sizes in addition to just features. 

### ISSUE THREAD

**Issue by ermish** [GoogleChromeLabs/tooling.report#397]
Title says it all. 

Feature comparisons are helpful, but results should also be compared. 
For example, if one tool builds twice as fast or produces much smaller bundles, it should be a significant key decision making point 👍

**Comment by surma** [comment]
We are consciously and actively excluding things like build time from the scoring, as outlined in the [About](https://bundlers.tooling.report/about/) section:

“Tests should be user-centric. The production impact of DX (build times, hot reloading, etc) is indirect and often subjective, so these are not currently represented.”
