### ISSUE TITLE
How can I remove unused JavaScript from my website?

### ISSUE THREAD

**Issue by Skyadav1996** [GoogleChromeLabs/tooling.report#402]
My website [www.studentsofeconomics.com](www.studentsofeconomics.com) shows the error of "remove unused javascript". Can I resolve this?

**Comment by ajayrpatil1713** [comment]
How can I remove unused JavaScript from my website?

**Comment by jakearchibald** [comment]
The extra JS is likely part of a module or library that you're only using a small part of. This will help you identify it https://developers.google.com/web/tools/chrome-devtools/coverage

**Comment by ajayrpatil1713** [comment]
Thank u so much..
