### ISSUE TITLE
Small update for Parcel

### ISSUE THREAD

**Issue by mischnic** [GoogleChromeLabs/tooling.report#409]
~(These are in the nightly version, not sure if that's a problem...)~

- https://bundlers.tooling.report/non-js-resources/css/source/
	- The linked issue is fixed. Sourcemaps aren't emitted anymore for inline assets.
- https://bundlers.tooling.report/non-js-resources/css/url/
	- The linked issue is fixed, importing CSS as a URL works correctly now.
- https://bundlers.tooling.report/transformations/dead-code-dynamic/
	- https://v2.parceljs.org/features/code-splitting/#unused-exports

**Comment by surma** [comment]
When we started this project we agreed the Parcel gets an exception wrt to our “stable” rule and the beta releases of v2 are allowed. Nightlies are too frequent to keep up with.

That being said, if you cut a new beta we can update a bunch of tests. Happy to review here!

**Comment by mischnic** [comment]
Fair enough!

**Comment by mischnic** [comment]
> That being said, if you cut a new beta we can update a bunch of tests

beta 2 was updated yesterday
