### ISSUE TITLE
The "Add" card linking to contributing is larger than the other cards

### ISSUE THREAD

**Issue by mischnic** [GoogleChromeLabs/tooling.report#417]
This is probably not intentional?

<img width="1013" alt="Bildschirmfoto 2021-04-20 um 12 51 42" src="https://user-images.githubusercontent.com/4586894/115384298-2a9e7380-a1d7-11eb-97b1-61ce748c3735.png">

https://bundlers.tooling.report/code-splitting/

Chrome 90.0.4430.72, macOS

**Comment by argyleink** [comment]
thanks for calling out the regression 👍🏻 

During dev builds and even in local production builds, I can't get the generated CSS file to be missing `padding: 0` on that contribCard. I'm only seeing in production, a style is omitted or purged somewhere along the way, even though it's clearly authored in the stylesheet as `padding: 0` in [collection.css#L50](https://github.com/GoogleChromeLabs/tooling.report/blob/dev/static-build/pages/test/collection.css#L50)

**Comment by developit** [comment]
This was fixed in #403 but never deployed. I've just deployed and it is now fixed on the live site.
