### ISSUE TITLE
Removed Unused Javascript & CSS

### ISSUE THREAD

**Issue by uzairhussain1090** [GoogleChromeLabs/tooling.report#426]
If if remove unused javascript from my website I am facing an error how can i remove unused javascript and css because my website speed is very slow.

**Comment by uzairhussain1090** [comment]
Why?

**Comment by surma** [comment]
You seem to be asking questions about _your_ website. This is the issue tracker for tooling.report.

If you run into issues, please open an issue with the build tool that is performing dead code elimination for you.
