### ISSUE TITLE
Better hero image illustrations

### ISSUE THREAD

**Issue by ziyafenn** [GoogleChromeLabs/tooling.report#437]
Hey guys,

What if we use custom-made hero-image illustrations for each section of the tests? Obviously, current illustrations do not depict anything that this website and its sections are about. 

I was thinking of illustrations with simple shapes and solid colors. A style that everyone can contribute to, without a need in having advanced graphic design skills. And illustrations that probably can better help a person to capture what the test/section is about.

As an example, I created a quick illustration for the code-splitting section, just to give you an idea.
![code-splitting-example](https://user-images.githubusercontent.com/314302/126125475-b1b5a3a3-a066-4896-9238-3b3d26c3632b.jpg)

I'm by no means a professional graphic designer, but i could definitely create quite few illustrations like this and create pull requests for each section. I can also upload the source files in `.sketch` or figma so everyone has access and can edit those images whenever needed.

I learned a lot about FE build tools, thanks to you :)

**Comment by argyleink** [comment]
While the hero images may not be directly or abstractly depicting aspects of the content, I don't think they need changed. 

We **are** looking for images like what you've demonstrated here on the Squoosh project. A marketing page wants to show compression, conversion, etc with shape / abstract visuals. You interested in pivoting the work to another repo?

**Comment by ziyafenn** [comment]
@argyleink sure, why not. If you could give me a link to the issue and a branch on Squoosh repo, I could take a look.

**Comment by argyleink** [comment]
turns out there's no issue created yet, it's still in a rough draft idea and not really in an actionable or assignable state. i can ping back here tho if/when the issue gets created and the need officially arises??

**Comment by ziyafenn** [comment]
Sure think @argyleink, ping me whenever you have more info.
